apiVersion: 1
datasources:
  - name: jaeger
    type: jaeger
    uid: "jaeger-datasource"
    url: http://jaeger:16686
    access: proxy
    editable: true

  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true

  - name: loki
    type: loki
    url: http://loki:3100
    access: proxy
    editable: true
    jsonData:
      derivedFields:
        - name: "traceId"
          datasourceUid: "jaeger-datasource"
          matcherRegex: "([a-f0-9]{32})"
          url: '$${__value.raw}'
          internalLinkEnabled: true