server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: default

scrape_configs:
  - job_name: services
    static_configs:
      - targets: [localhost]
        labels:
          job: services
          env: dev
          __path__: /host/logs/*.log

    pipeline_stages:
      - multiline:
          firstline: '^{"'
          max_wait_time: 3s
      - json:
          expressions:
            level: level
            service: service
            traceId: traceId
            logger: logger_name
            msg: message
      - timestamp:
          source: ts
          format: RFC3339Nano
      - labels:
          level:
          service:
          traceId:
          logger:
