server:
  port: 8083

spring:
  application:
    name: payment-service
  transaction:
    default-timeout: 20
  datasource:
    url: jdbc:postgresql://localhost:5432/demoEventDrivenDB
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 10000
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: payment
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    schemas: payment
    locations: classpath:db/migration/payment
    connect-retries: 3
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true
        otel.instrumentation.kafka.enabled: true
        metrics.recording.level: INFO
        metrics.sample.window.ms: 5000
        compression.type: snappy
        retries: 3
    consumer:
      group-id: payment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      max-poll-records: 500
      fetch-min-size: 1024
      fetch-max-wait: 500
      auto-offset-reset: earliest
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        otel.instrumentation.kafka.enabled: true
        metrics.recording.level: INFO
        metrics.sample.window.ms: 5000
        max.poll.interval.ms: 300000

logging:
  level:
    org.hibernate.SQL_SLOW: info
  file:
    name: ./observability/temp/payment-service.log
  charset: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    enabled: true
    service-name: ${spring.application.name}
    sampling:
      probability: 1.0
  metrics:
    enable:
      kafka: true
    export:
      prometheus:
        enabled: true
      otlp:
        enabled: false
  observations:
    application:
      name: ${spring.application.name}

observability:
  serviceName: ${spring.application.name}
  environment: dev

testmode:
  enabled: true
