server:
  port: 8079

spring:
  application:
    name: booking-service-query
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/booking_query_db}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true
        otel.instrumentation.kafka.enabled: true
        metrics.recording.level: INFO
        metrics.sample.window.ms: 5000
    consumer:
      group-id: booking-command-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        interceptor.classes: com.mengo.architecture.metadata.MetadataConsumerInterceptor
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        otel.instrumentation.kafka.enabled: true
        metrics.recording.level: INFO
        metrics.sample.window.ms: 5000

logging:
  file:
    name: ./observability/temp/booking-service-query.log
  charset: UTF-8

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    enabled: true
    service-name: ${spring.application.name}
    sampling:
      probability: 1.0
  metrics:
    enable:
      kafka: true
    export:
      prometheus:
        enabled: true
      otlp:
        enabled: false
  observations:
    application:
      name: ${spring.application.name}

observability:
  serviceName: ${spring.application.name}
  environment: dev

testmode:
  enabled: true