server:
  port: 8084

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb
      database: productdb
  datasource:
    url: jdbc:postgresql://localhost:5432/demoEventDrivenDB
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: product
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    schemas: product
    locations:
      - classpath:db/migration/product
      - classpath:db/seed
    connect-retries: 3
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true
        otel.instrumentation.kafka.enabled: true
        metrics.recording.level: INFO
        metrics.sample.window.ms: 5000
    consumer:
      group-id: product-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        otel.instrumentation.kafka.enabled: true
        metrics.recording.level: INFO
        metrics.sample.window.ms: 5000

logging:
  file:
    name: ./observability/temp/product-service.log
  charset: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    enabled: true
    service-name: ${spring.application.name}
    sampling:
      probability: 1.0
  metrics:
    enable:
      kafka: true
    export:
      prometheus:
        enabled: true
      otlp:
        enabled: false
  observations:
    application:
      name: ${spring.application.name}

observability:
  serviceName: ${spring.application.name}
  environment: dev